apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: vbar-viber-bot
  labels:
    app: analytics-service
    component: analytics
    service: analytics
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3003
  sessionAffinity: None








