apiVersion: v1
kind: Service
metadata:
  name: web3-service
  namespace: vbar-viber-bot
  labels:
    app: web3-service
    component: web3
    service: web3
spec:
  type: ClusterIP
  selector:
    app: web3-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3004
  - name: grpc
    protocol: TCP
    port: 50052
    targetPort: 50052
  sessionAffinity: None

