apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: vbar-viber-bot
  labels:
    app: admin-service
    component: admin
    service: admin
spec:
  type: ClusterIP
  selector:
    app: admin-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  sessionAffinity: None





