apiVersion: v1
kind: Service
metadata:
  name: mongodb-bot
  namespace: vbar-viber-bot
  labels:
    app: mongodb-bot
    component: database
    service: bot-db
spec:
  type: ClusterIP
  selector:
    app: mongodb-bot
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None
  publishNotReadyAddresses: false






