apiVersion: v1
kind: Service
metadata:
  name: mongodb-web3
  namespace: vbar-viber-bot
  labels:
    app: mongodb-web3
    component: database
    service: web3-db
spec:
  type: ClusterIP
  selector:
    app: mongodb-web3
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None
  publishNotReadyAddresses: false

